### ISSUE TITLE
initially, The second slide is displayed first before returning to first

### ISSUE THREAD

**Issue by Byloor** [antoniandre/vueper-slides#53] opened 2019-11-08 13:08 UTC
When the page is loaded, the slide 2 is displayed for a short second before jumping to first. Is there a way to avoid this? Or is this intended. If it is intended behavior. Could you provide an option to disable this behavior (if there is not already present). 

Note: adding `infinite:false` would remove this behavior ofcourse. but I do not want to disable the infinite scroll option.

This behavior can also be seen in the provided demo.

**Comment by Byloor** [comment] 2019-11-08 13:23
My bad.  adding the  `:infinite="false" `to `vueper-slides` component, resolved it.

**Comment by antoniandre** [comment] 2019-11-11 12:29
Hi @Byloor, Thanks for reporting, I also noticed this regression. 
This will fix this soon, for now I am currently working on another issue.
Will let you know.

**Comment by antoniandre** [comment] 2019-11-22 07:18
Hi @Byloor, 
This issue should be resolved in the version 2.0 just released.
Please check the release notes in the documentation.

Let me know if it solves it for you.

**Comment by Byloor** [comment] 2019-11-26 10:20
Thanks. I will take your word for it. I dont want to update the package yet. If it works for others, this issue can be closed:)

**Comment by az-iar** [comment] 2019-11-27 07:29
not working on my side. currently using v2.0.3. autoplay also seems to have problem

**Comment by antoniandre** [comment] 2019-11-27 11:18
Thanks @az-iar, can you please share your code and environment (Vue Cli, webpack, Nuxt...) and more details about what it does wrong - a reproduction link would be even better.

**Comment by antoniandre** [comment] 2019-12-15 10:44
Closing due to inactivity. Please reopen if not solved.

**Closed by antoniandre** 2019-12-15 10:44 UTC
Labels: bug
