### ISSUE TITLE
Accessibility 

### ISSUE THREAD

**Issue by bondzula** [antoniandre/vueper-slides#1] opened 2018-07-11 16:27 UTC
Can we name bullets for better accessibility?

**Comment by antoniandre** [comment] 2018-07-16 06:13
Yes, it will be in the next release coming soon.
I will add aria-label on arrows, role="tablist" on bullets wrapper and role="presentation" on each bullet.
Is it what you suggested?

**Comment by antoniandre** [comment] 2018-07-16 16:22
Version 1.6.0 is now equipped with a load of accessibility attributes.
- aria-label="Slideshow" on slideshow container
- aria-live="polite" on slides container
- aria-hidden true/false on each slide
- aria-label previous/next on arrows
- role="tablist" aria-label="Slideshow navigation" on bullets container

____

__Caution:__ 
From version 1.6.0 the styles must be imported from an external file. Refer to the [installation part](https://antoniandre.github.io/vueper-slides/documentation/#installation) in the documentation.

**Closed by antoniandre** 2018-07-16 16:22 UTC

**Comment by guirisan** [comment] 2019-10-30 20:18
The same is happening me, until the first click is done in some arrow or bullet, keyboard arrows won't work. In the project [codepen](https://codepen.io/antoniandre/pen/jevjoQ) the issue is also present.

Click on the image didn't work also, thanks in advance.

**Comment by antoniandre** [comment] 2019-11-03 02:26
Hi @guirisan, This is the normal behavior.
You need to first have the focus on a button of the slideshow to be able to navigate with arrows.
This is can also be done with the tab key - as a normal accessible app.

If you want to be able to navigate through the slideshow with arrows from the beginning you can set the focus on one of the slideshow button from the `ready` event. But this is not something that should be done from the `vueper-slides` library as this is your decision to put the slideshow on focus on page load. 
But I don't recommend doing so neither - imo, for accessibility, the focus should stay at the first focusable element of the page. Then the user can tab to wherever they want.

Hope it clarifies a bit.

**Comment by guirisan** [comment] 2019-11-14 15:22
Hey, thanks a lot for the answer!

Yeah I understand that accessibility approach but the people who gave me
this job wants this behaviour as it's just a gallery page where the only
thing you can do is view photos.

Great job with the plugin, bye!

Missatge de Antoni <notifications@github.com> del dia dg., 3 de nov. 2019 a
les 3:26:

**Comment by antoniandre** [comment] 2019-11-18 02:11
Thanks @guirisan for the feedback and yes then it makes sense.
So from the ready event, trigger the focus on the first slide bullet:

```vue
<vueper-slides @ready="focusFirstBullet()">
  <vueper-slide v-for="i in 5" :key="i" :title="i.toString()"></vueper-slide>
</vueper-slides>
```

```js
// In your component methods.
focusFirstBullet () {
    // Give it time to be in the DOM.
    setTimeout(() => {
        document.querySelector('.vueperslides__bullets button:first-child').focus()
    }, 200)
}
```

Here is a demo: https://codepen.io/antoniandre/full/mddaWze, and editable here: https://codepen.io/antoniandre/pen/mddaWze.
