### ISSUE TITLE
Vue 3, installation - css

### ISSUE THREAD

**Issue by songoo** [antoniandre/vueper-slides#115] opened 2020-11-09 22:36 UTC
In my component on develop I use as stated in guide :
```
import { VueperSlides, VueperSlide } from 'vueperslides'
import 'vueperslides/dist/vueperslides.css'
```
Everything works but when i release with cli "npm run build"
"vueperslides.css" is missing in dist files.

Tnx for any advice :)

**Comment by antoniandre** [comment] 2020-11-10 04:27
Hi @songoo, 
Hmmm, that's weird, it should work. 
I just tried to build for prod a site that uses Vueper Slides and Vue 3 and it all ships correctly.
So it could come from a misconfiguration somewhere. 

- Do you use the latest Vueper Slides (`vueperslides@next`) and latest Vue 3?
- Do you use vue-cli, or nuxt or anything else?
- Do you use other external Vue 3 libs which include the CSS correctly?

**Comment by songoo** [comment] 2020-11-10 12:42
Hello, its fresh vue-cli installed 3days ago, then from choices manual install with router and vuex.
I have route to homepage, and in it I have 
import { VueperSlides, VueperSlide } from 'vueperslides'
import 'vueperslides/dist/vueperslides.css'

where it works on localhost , I have setting for /dist/ folder in vue config, since on production I have vue in sub-folder named dist. Then on production i have html where I have manually copied includes from generated index page.

**Comment by antoniandre** [comment] 2020-11-10 23:52
This is then a misconfiguration,

In your vue.config.js you should have something like `publicPath: process.env.NODE_ENV === 'production' ? '/your-prod-dir' : ''`.

Then in your Vue router something like this:
```js
const router = createRouter({
  history: createWebHistory(process.env.BASE_URL),
  routes
})
```

The base URL will be accurate for both local and prod builds.
Hope it helps!

Please close the issue if you fix this.

**Comment by songoo** [comment] 2020-11-12 18:39
Hi, tnx much for response but if I do as adviced, mi main page will change from 
www.page.com  to
www.page.com/dist

Although slider works, the form of web link its not acceptable sadly :(

**Comment by songoo** [comment] 2020-11-12 21:47
Anyways I went with hope on vue3 discord to get advice, and they adviced me that /dist in url is standard behavior and if I want to do otherwise I have to create .htacces .
Althought am not much good with it and google atempts failed pretty much T.T
+ Encountered another weird behavior that even with all working in www.page.com/dist, its not really working on intital load of "www.page.com" its automatically changes url to /dist but do not load any imported styles, so even standard installation does not work for me on production T.T


Anyways I get it working in the end like this :

_"publicPath: '/dist'" and "history: createWebHistory(process.env.BASE_URL)" where project is in "/dist" folder, so page goes www.page.com/dist. All work but. I go to "www.page.com" it redirects to "/dist" but when look in html it does not generate "/dist/css/chunk-vendors.css" so all imported css is missing. But when I hit refresh (going directly to www.page.com/dist)  chunk-vendors.css is loaded. By default vendors.css is not in generated index.html so I guess its done by js. So i got evil thought of just paste that vendors.css link manually to my production index.html aand it works, althought when going to /dist url directly I end up with loading this style 2 times lol.
Then I got even more evil thought and changed to 'history: createWebHistory("/")' , rebuilded for production and now i have nice www.page.com and even all imported styles are working (with that style link pasted in manually), just have some feeling I will burn in hell._

**Comment by antoniandre** [comment] 2020-11-17 03:16
Hi @songoo,

Sorry the problem is a misconfiguration in your Vue project not in the Vueper Slides library. For that I am closing the issue, even if I can still give you advice here.

This is how it works in a regular project to build (I'll show you the example of the Vueper Slides documentation):

**vue.config.js**
```js
module.exports = {
  publicPath: process.env.NODE_ENV === 'production' ? '/vueper-slides' : '',
  // ...
}
```

The above config sets a different site URL for dev and prod. the prod `/vueper-slides` is there because on the final URL in Github this is the path that must be set (E.g. `https://antoniandre.github.io/vueper-slides`).

when building with Vue Cli `npm run build` the output goes into `/dist` folder (by default) and the build is set for prod by default (so `process.env.NODE_ENV = 'production'`).

Now, if you try to go in that dist folder in your localhost, the vue-router using the same `publicPath` will fail because on your localhost `your-proj/dist` is a different base URL than `/vueper-slides` as set in the config. So it will only work in the final server where the base url can be matched. 
 
As said earlier, your vue-router should always be set to (this config is for vue-router@next - for Vue 3):

```js
const router = createRouter({
  history: createWebHistory(process.env.BASE_URL),
  routes
})
```

So that it follows the base URL you set in a single place, in your vue config.

Regarding the `.htaccess`, it is a common practice to set up redirections in it so that on your final server, accessing `https://antoniandre.github.io/vueper-slides/a-sub-page` directly will be redirected to your index.html that can load the vue-router which will handle the route matching of what you entered in the URL.

Without this .htaccess, the Vue router cannot be reached from a sub-folder since it does not exist on the server (it's a virtual route using rewriting engine), it would result in a not found URL.

Here is a simple example of `.htaccess`:

```
Options +FollowSymlinks
Options -Indexes

RewriteEngine On
RewriteRule \.(js|css|map|jpe?g|svg|gif|png|eot|ttf|woff2?)(\?.*)?$ - [NC,QSA,L]
RewriteRule .* index.html [NC,QSA,L]
```

What is important in that is the last line redirecting anything to index.html (which is generated from your vue-cli build).
The previous line allows any asset file to not be redirected (no asset file should be handled by vue-router).

Hope it helps you understand! ;)

**Closed** 2020-11-17 03:16 UTC
Labels: vue 3

**Comment by songoo** [comment] 2020-11-17 11:54
Hi , tnx much for advice!
I got things working by solution mentioned in cursive text above.
Thing is I do not use generated index.html, but took its scripts and included them into index.php of existing php framework. And whole vue dist folder which normally should be in root "www" folder I moved into subfolder in production (named it "dist" but could be named in any way) so it wont mix with my framework already in there.  And there this problem started that even if page successfully loaded since php framework did load index.php, vue javascript after load did additional change to url to "www.../dist" that happened after the page sucessfully loaded index.php .  

Anyways with router set to "/" and by including path to generated css file it works ok. The whole problem was caused by vue not adding <link> to its generated css by some reason.
