### ISSUE TITLE
Cannot read property 'css' of undefined

### ISSUE THREAD

**Issue by whoisme555** [antoniandre/vueper-slides#98] opened 2020-07-07 19:53 UTC
![image](https://user-images.githubusercontent.com/50149901/86835144-afb20500-c069-11ea-8706-672211161247.png)
I'm sure this has something to do with my specific configuration as I'm handling the abnormal task of incrementally converting a legacy solution to vue (which makes giving a reproducible repository very difficult), but I'm getting this error and wasn't sure how to fix it.

It works if I remove the vueper imports, but as soon as I add them, the site no longer loads with the errors in the pictures above. Any idea what I can do?

**Comment by antoniandre** [comment] 2020-08-25 00:45
Hi @whoisme555, sorry for late reply.
Have you found the cause?
If you haven't you can create a Codesandbox with similar environment and I will look at it.
But like that, it's hard to tell, no other similar issue or scenario comes to my mind.
It looks like Mootools is involved in the first error.

**Comment by whoisme555** [comment] 2020-08-25 01:24
> Hi @whoisme555, sorry for late reply.
> Have you found the cause?
> If you haven't you can create a Codesandbox with similar environment and I will look at it.
> But like that, it's hard to tell, no other similar issue or scenario comes to my mind.
> It looks like Mootools is involved in the first error.

Thanks, but no chance of giving a reproducible environment. Has to be related to the incremental conversion. Something is causing something to break but I gave up and made my own vue wrapper on another slider.

**Comment by antoniandre** [comment] 2020-08-25 01:27
Ok, sorry to hear that then.
I am closing the issue then, thanks for replying anyway! :)

**Closed by antoniandre** 2020-08-25 01:27 UTC
